### ISSUE TITLE
Project Rename

### ISSUE THREAD

**Issue by lcherone** [lcherone/Conext#1]
Throw ideas as to what to call it please lol, Deval was my first thought as, Dev because its kind of useful for Developing web projects and uses `eval` in the API data endpoints part, but over the last week it feels kinda lame lol.. I also not keen on calling it LXD Web Panel or UI

Be funny or rude.. Its all good.

**Comment by bmullan** [comment]
What is the "goal" of the new project vs the old ?

**Comment by bmullan** [comment]
Boy this is like naming a new dog or a new kid ;-)

OpsCon - Operations Control ?
ConCenter - Control Center ?
LXDCenter 

I'll think about some others.

**Comment by lcherone** [comment]
> What is the "goal" of the new project vs the old ?

Its not like the LXD-ui project, this one is a decentralised web interface for servers mainly aimed at web hosting projects (port and web forwarding with Lets encrypt, tasks and custom API endpoints). Where you install an agent on the server which opens up a rest and RPC API's so it can be extended to cater for project deployments etc.

I like them names, thanks.

**Comment by bmullan** [comment]
like the new name!

**Comment by lcherone** [comment]
@bmullan Thanks.. its been a right pain switching it all over.
