### ISSUE TITLE
Container's console doesn't work in Safari

### ISSUE THREAD

**Issue by talyguryn** [lcherone/Conext#10]
I can not type anything. No errors in console. Works fine in Chrome and Safari Technology Preview.

![image](https://user-images.githubusercontent.com/15259299/40796736-b7aa6684-650e-11e8-925e-14959221faae.png)

**Comment by lcherone** [comment]
It will be an issue with xterm.js - I did have a quick look and found:

https://github.com/xtermjs/xterm.js/issues/346

This project uses xterm@3.4.1

Though if the websocket died it could cause the issue.
