### ISSUE TITLE
<UI> Enhancement container snapshot description

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#104]
Hi lcherone,
can you add ad snapshot description field? So snapshots within the containter tab can have some additional information?

Best regards

Meywether

**Comment by lcherone** [comment]
I did have a play to see how it would look, but on a long description it messes up the table, and there is not much space to work with as-is :( 

I'll be adding rename snapshots soon, also remove the container name from the start, and put the buttons in a drop down, so it should all fit in.

**Comment by lcherone** [comment]
I've added the rename and changed the buttons. Went to add the description part but snapshots don't have a PATCH endpoint, so you cant edit the `user.*` properties. But you can rename them what you like (with whitespace).
