### ISSUE TITLE
BUG <UI> Profile

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#105]
Hi lcherone,
I think I found a similar bug connected to the same issue at the networks tab.

The standard lxd bridge and default storage pool does not show up witihn the new profile page.
![image](https://user-images.githubusercontent.com/39849054/41277204-0f0814f2-6e16-11e8-909f-752c6dc3db8b.png)

Best regards
Meywether

**Comment by lcherone** [comment]
Cool, I've tweaked it abit so should be working now.

Note the whole devices part/tab is not working yet or profiles, I'm currently working on that part.

**Comment by Meywether** [comment]
> Note the whole devices part/tab is not working yet for profiles, I'm currently working on that part.

Got it !

**Comment by lcherone** [comment]
Devices & idmap added to profiles now.
