### ISSUE TITLE
<Enhancement> install.sh

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#106]
Hi lcherone,
found another "problem" within install.sh

the minimal installation of ubuntu 18.04 does not have a lxd group by default.

Please consider adding: `addgroup lxd` to your install.sh

Best regards 
Meywether

**Comment by lcherone** [comment]
Thanks for pointing it out, I've added an additional check to install.sh

```
if [ ! $(getent group lxd) ]; then
    addgroup lxd
fi
```
