### ISSUE TITLE
BUG ?<UID Mapping>

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#107]
Hi lcherone,
after several hours of trying I got a really weird issue with the behavior of UID Mapping.

After attaching and mapping I have to restart the container. 

So if i use the "restart all" or "restart" button -> nobody : nogroup
but
if i use containerX "stop" and afterwards "start" - > valid mapping

Really weird, but it took me really long to figure out the problem :)

Best regards 
Meywether

**Comment by lcherone** [comment]
I think that's because containers need to be stopped first, so it can remap the ids. 

Do you think I should make it that the container must be stopped before allowing the toggling?

**Comment by Meywether** [comment]
Hi,

> I think that's because containers need to be stopped first, so it can remap the ids.

It also works if the container runs.
But it has to be stopped and not restarted by using the "restart" button.


> Do you think I should make it that the container must be stopped before allowing the toggling?

From a usability point of view, it would be  more logical to stop them before toggling. We have to test it, if afterwards by using "restart all" it works too. Or if it is possible to do it like: 

1.) Clicking on tab id mapping 
2.) Popup "Toggling only on stopped container possible -> Do you want to start ?
3.) toggling X ids
4.) Button with "Apply" and "apply and restart"

The would be my suggestion!
Thanks in advance!

All the best!
Meywether

**Comment by lcherone** [comment]
Cool, I've added a check if the container is running it will show an alert where the user can stop the container and then toggle the items, once done can start the container again.. if the container is already stopped won't show the alert.

**Comment by Meywether** [comment]
Hiho, sorry but I have to reopen this issue.
Whyever, after toggling I was not able to start the container again. Console was empty....
Sorry.

Kind regards 
Armin

**Comment by Meywether** [comment]
to be more specific,
1.) tab id mapping -> stopped container -> works
2.) toggled some users
3.) clicked the new start button 
4.) Message: "successfull started" -> meep not started
5.) tried restarting, start all and soo on -> meep not working

**Comment by Meywether** [comment]
Strange - it seems, that only one container before one update is affected. Have to test it with another one after another update.

**Comment by lcherone** [comment]
Then its mapping correctly as noted in the alert, try starting the container with cmd line, then read the error it says. (you might need to look at the log). Most likely either groups or user ids are not in both container and host.

If I try it with `ubuntu` user, then its working as expected. If I map `mysql` user, then the container wont start as `mysql` is not installed so no user/group.. 

tbh it's a tricky thing to do, and all Conext is doing is setting `raw.idmap`, if it's not working its your need to manually find out why. It's basically a LXD issue.

**Comment by Meywether** [comment]
Stupid question:
with snap lxd installed, How do I run lxc / lxd commands?

![image](https://user-images.githubusercontent.com/39849054/41311274-1604b5a8-6e84-11e8-93d5-52a3e593c679.png)

**Comment by Meywether** [comment]
One more thing, after "starting" the container inside the id mapping tab, can you reload the container view automatically?

**Comment by Meywether** [comment]
Its really weird. You were right. 
two users prevent the container from starting, the problem ist, that they are both valid users...

![image](https://user-images.githubusercontent.com/39849054/41312036-58c5d37a-6e86-11e8-9ede-782aeb364afb.png)

Mmh damit how do I ask snap lxd ? lxc ls and so on not working ...

**Comment by lcherone** [comment]
Unless there is a link in sbin/bin to the snap like `/usr/bin/lxc` then it wont find it, this should of been added by the install, then just either open a new shell.

You can add the link to `/snap/bin/lxc` like `ln /snap/bin/lxc /sbin/bin/lxc`.

Then its `lxc list` not `lxc ls`

Is this on a system where my install.sh script has run? Or are you just manually doing things?

**Comment by Meywether** [comment]
> You can add the link to /snap/bin/lxc like ln /snap/bin/lxc /sbin/bin/lxc.
Yeah it was my fault and you mentioned it:

>Then its lxc list not lxc ls 
Totally right my fault

> Is this on a system where my install.sh script has run? Or are you just manually doing things?

Nope install script! Asap I get to my pc @ work tomorrow I will get the log !

Thanks !!! You are really great thanks !
