### ISSUE TITLE
<UI> Enhancement Proxy Devices

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#113]
Hiho,
i have two more features which would be really helpful.

At first I call it a general proxy device, which takes the ip address from the assoc. container and just takes the port number. 

And secondly can we make the ip adress of the container manageable from the UI ? so a switch between dhcp and manual ip setting? Because manually updating proxy devices after restart can be easily overseen.

Best regards
Meywether

**Comment by lcherone** [comment]
> At first I call it a general proxy device, which takes the ip address from the assoc. container and just takes the port number.

I can look into changing the proxy tab that it's more simpler, currently, you define the proxies and then attach them, like other devices. But doing it from each containers tab is doable. I don't really want to get into managing stuff from that modal. First, is that if you click off you loose changes, secondly there is simply no room.

> And secondly can we make the ip adress of the container manageable from the UI ?

It is, by setting up the network and adding it as a device?

> A switch between dhcp and manual ip setting? Because manually updating proxy devices after restart can be easily overseen.

It's not as simple as that, you would need to setup the network first anyway and how LXD devices work you would need to add a `block`'ing device to eth0 and then add your own network and toggle it. Then add the different DHCP settings and IP setup from that little modal, which seems alot that modal already loads abit slow. If you want to have custom networks for each container then define the devices and a block device then toggle it.

Not sure what you mean about updating proxy, just add a larger expiry, the IP shouldn't be changing after a restart.

I'm trying to keep things clean and simple to understand, if devices are grouped together in one place and the ONLY place you can add and create, and then you simply toggle them on and off in the container and profiles then its easy to understand and fits in with how the LXD config works. Doing opinionated functionality/processes or for example updating networks whilst adding somthing to a containers on the fly and moving away simply inserting the device, network, profile in the containers config property is not something I wanna do.

**Comment by Meywether** [comment]
> It is, by setting up the network and adding it as a device?

Whhops that opportunity I forget to think about!

Thanks, I got your point and understand it !

**Comment by Meywether** [comment]
Hiho,
I do have another suggestion which can fit our both needs.
Within Proxy devices, it only make sense to create proxy from host ip to container ip.
Would it be possible to leave the free entry field if needed whyever and add to dropdowns where the container names are listed and after clicking on it the ip adress is pasted into the input field?

Kind regards
Meywehter
