### ISSUE TITLE
Manage Files

### ISSUE THREAD

**Issue by lcherone** [lcherone/Conext#118]
New feature added for containers, you can now manage files. 

Not advised you use this for serious things, but its a nice little feature for quickly changing something or viewing a log without bringing up the console.

**Has some issues:**

 - If the file is empty it thinks its a directory, so won't load the file. Not sure how to work around this, as headers are not returned in cli.
 - Cant add or remove directories unless the directory is empty, then you need to traverse backwards deleting the directories and files.
 - Cant rename files.
 - Files added are owned by root.

If you already have Conext installed, then you need to update the Plinker LXD composer package, so go in `/var/www/html` and run `composer update`

**Screen: (sorry it's laggy.. I'm in swap ;p)**

![peek 2018-06-13 04-58](https://user-images.githubusercontent.com/3892806/41329916-581a0e0e-6ec8-11e8-8833-556b5d935d75.gif)

Any issues, comment below...
.

**Comment by Meywether** [comment]
Hi lcherone,
very nice  idea! 
Thanks a lot.

**Comment by Meywether** [comment]
Works as expected! Very nice. Would it be possible to add functionality to make it executeable? 
Best regards!

**Comment by lcherone** [comment]
Its possible, but the cli way is limited as it does not return **any** information about the file, so ya cant know what the attributes are already. In the backend its using `lxc file push -p --mode=644 --uid=0 --gid=0 ...` which is why its limited.

On the API you can do it, but the system does not use the API so it cant get the headers which are returned. 

Would of been nice if LXD for a returned directory listing, it added info about the file as an object and not just the name, then upon hitting a file it returned the contents as normal, then it wouldn't need the headers, would work for both then.

**Comment by Meywether** [comment]
yeah I get the problem! But still really nice :) well done thanks a lot!

**Comment by lcherone** [comment]
No probs, it's nice that you can edit files on a stopped container. It might come in handly.

Keep an eye out for `logs` tab, ill prob add it today or tomoz. Was looking into the `metadata` stuff but I'm not sure what it does lol.

**Comment by Meywether** [comment]
mmh whats about a container syslog tab? 
or get it in conflict with some permissions?
