### ISSUE TITLE
Update Question

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#123]
Hi lcherone,
I have a question,
expect following situation:

You have some website running at /var/www/html/xxx
and conext.
You make git pull

What happens to the other directories ?
I do not want to get them removed :)

If they get removed we should consider moving conext into an seperate folder..
Best regards
Meywether

**Comment by lcherone** [comment]
Really there shouldn't be a website running in that directory, **put other sites in containers**. The idea is you keep the host clean.

Though.. it will be ok as long as you don't change any files related to the project, or you will have issues and need to stash or commit the changes before pulling.

**Comment by Meywether** [comment]
Totally right ! Thanks !

**Comment by lcherone** [comment]
Also nginx is managed by the panel, any changes you make will be overwritten.
