### ISSUE TITLE
BUG <Proxy Devices>

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#126]
Hi lcherone,
if I try to detach a proxy device I get this error message :
![image](https://user-images.githubusercontent.com/39849054/41371923-1b5e12e2-6f4c-11e8-9220-bffccf9948b0.png)

Best regards
Meywether

****
Update:
This error seems to connected to anything else, I am not sure, I try to reproduce it. It seems that a combination can do it. It happened to me twice.

**Comment by lcherone** [comment]
I think its fixed now keep an eye out to see if it happens again. 

I know what causes it, turning inbound suffix e.g `512MB` into just `512` so vue can use it and then on save, adding the suffix back, without breaking the view model and producing console errors. 

When you attach a device you can use PATCH, but when you remove a device you must use PUT, which you need to replace the whole container config. Which then you need to infix/outfix all the correct suffix.. juggling game..lol

**Comment by Ragitagha** [comment]
> When you attach a device you can use PATCH, but when you remove a device you must use PUT, which you need to replace the whole container config. Which then you need to infix/outfix all the correct suffix.. juggling game..lol

Uff thats seems hard -> reading all the config, modify, and back into it.

Strange ^^ But thanks !

**Comment by Meywether** [comment]
> When you attach a device you can use PATCH, but when you remove a device you must use PUT, which you need to replace the whole container config. Which then you need to infix/outfix all the correct suffix.. juggling game..lol

Uff thats seems hard -> reading all the config, modify, and back into it.

Strange ^^ But thanks !

**Comment by lcherone** [comment]
Reopen if you have this issue again, closing for now.
