### ISSUE TITLE
<Enhancement> UI Container Profiles

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#127]
Hi lcherone,

may you please consider to change the list where I can change the Profile where the Container belongs to, from a multi checkbox list to a radiobutton list? 

If I tick two Profiles, it only takes one afterwards.

Best regards
Meywether

**Comment by lcherone** [comment]
I'm not sure I understand, :/

I've just tested it and it's adding removing profiles if the container is stopped.

Ill change it that container must be stopped to changed profiles, tbh I thought you could hot swap them.

**Comment by Meywether** [comment]
> Ill change it that container must be stopped to changed profiles, tbh I thought you could hot swap them.

That was the problem, I just testet it and yeah it has to be stopped!

Thanks a lot

**Comment by lcherone** [comment]
I've just added the change, so it needs to be stopped first.. Thanks for pointing it out :)

**Comment by Meywether** [comment]
THX!
