### ISSUE TITLE
How to add additional servers?

### ISSUE THREAD

**Issue by bmullan** [lcherone/Conext#13]
I haven't seen any documentation regarding steps to add additional servers.

Hitting the ADD SERVER button brings up the form

I have another server (Host2) that already has SNAP LXD installed and I'd like to ADD that server to my Conext running on Host1.

But .. 

- What "secret key" would I use for this additional server?  Is it the same one as on the first host which was provided by the running of install.sh.
- The additional server does have LXD configured to be accessed over the network
- What else needs to be installed on the Host2 server as I don't think I can just use "http://ip-host2:88"

**Comment by lcherone** [comment]
If you want to control additional servers and not just use them for [images](https://github.com/lcherone/Conext/wiki/Adding-Image-Remotes), then you need to install Conext on the server.

Once you done that add the server the panel as normal using the secret.

With an existing LXD server would have to manually install Conext with git, then run `composer setup`, which will run `.api/setup.sh`.. or you could dissect that script and run each part manually.
