### ISSUE TITLE
<Enhancement> UI ID Mapping

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#130]
Hi lcherone,
I suggest an filtering or sorting possibility within the ID Mapping tab.
Mapping filtering all system users with ID < 1000 and all users ID > 1000 and maybe filtering by input field.

Thanks in advance!
Best regards
Meywether

**Comment by Meywether** [comment]
ah! Sorry after hovering, I found the sorting arrow. But filtering would be nice!

**Comment by lcherone** [comment]
Added a filtering..
