### ISSUE TITLE
<BUG> Difference between LXC.conf in container dir on host and conext ID Mapping

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#131]
HI lcherone,
I found an issue conerning id mapping.

There are many differences between the lxc conf and the ui id mapping.

host: 
![image](https://user-images.githubusercontent.com/39849054/41459803-eb0c6d88-708a-11e8-93c9-f76c82c30930.png)

UI:
![image](https://user-images.githubusercontent.com/39849054/41459942-57aab51c-708b-11e8-90c1-fd1cb017d1dc.png)

Example difference: 

Look at Userid 1002 on host -> not mapped  ||  ui -> should be mapped
same with userid 1004

I tried to fix it manually but conext has overwritten my changes. So I cant say if the changes worked or not

Also there are multiple entries. 1004 for example.

I tried to insert this: 

lxc.idmap = u 1000 1000 1
lxc.idmap = g 1000 1000 1
lxc.idmap = u 1001 1001 1
lxc.idmap = g 1001 1001 1
lxc.idmap = u 1002 1002 1
lxc.idmap = g 1002 1002 1
lxc.idmap = u 1003 1003 1
lxc.idmap = g 1003 1003 1
lxc.idmap = u 1004 1004 1
lxc.idmap = g 1004 1004 1
lxc.idmap = u 1005 1005 1
lxc.idmap = g 1005 1005 1
lxc.idmap = u 1006 1006 1
lxc.idmap = g 1006 1006 1
lxc.idmap = u 1007 1007 1
lxc.idmap = g 1007 1007 1
lxc.idmap = u 1008 1008 1
lxc.idmap = g 1008 1008 1
lxc.idmap = u 1009 1009 1
lxc.idmap = g 1009 1009 1
lxc.idmap = u 1010 1010 1
lxc.idmap = g 1010 1010 1
lxc.idmap = u 1011 1011 1
lxc.idmap = g 1011 1011 1
lxc.idmap = u 1012 1012 1
lxc.idmap = g 1012 1012 1
lxc.idmap = u 1013 1013 1
lxc.idmap = g 1013 1013 1
lxc.idmap = u 1014 1014 1
lxc.idmap = g 1014 1014 1
lxc.idmap = u 1015 1015 1
lxc.idmap = g 1015 1015 1

Best regards
Meywether

**Comment by lcherone** [comment]
As mentioned before, Conext just applies a value to `raw.idmap` any changes to the actual config would be done by LXD.

**Comment by Meywether** [comment]
Hi lcherone,
I beg a pardon and I want to ask you if you can tell me my mistake:

Expect: Clean Ubuntu Desktop 1804 Installation
I created ten users starting from uid 1000 and ten home dirs.
I downloaded and executed you install.sh

I created a container test 
I created the same ten users within the container the gid starts with 1001000

In conext, I stopped the container and toggled all ids (ten) and wanted to start -> no way.
Trying just with some of them the last one for example or two of them, but never more than 5 of them -> container starts
May I ask you to try it and if it works, please tell me my mistake.

Thanks in advance!
Meywether

**Comment by lcherone** [comment]
You can only map up to 5, its a kernel limit. https://github.com/lxc/lxd/issues/3933

**Comment by Meywether** [comment]
aww that should be written in their documentation : [https://lxd.readthedocs.io/en/latest/userns-idmap/](https://lxd.readthedocs.io/en/latest/userns-idmap/)

But thanks anyway! That explain everything ^^

**Comment by lcherone** [comment]
No worries, I was unaware of it too, I've added the check it will be in next release.

**Comment by Meywether** [comment]
hopefully they can expand the limit as stgraber mentions in https://github.com/lxc/lxd/issues/3933#issuecomment-336191492 I gonna ask :)

**Comment by lcherone** [comment]
Changed it to only apply display a message to  < 4.15 kernels

**Comment by lcherone** [comment]
@Meywether Added container logs, so you won't need to jump on cmd line to find out why it didn't map/boot etc now.

![screenshot-10 158 250 203-3000-2018 06 16-04-39-40](https://user-images.githubusercontent.com/3892806/41495452-9518eb28-711f-11e8-830a-126f0829d44b.png)
![screenshot-10 158 250 203-3000-2018 06 16-04-40-05](https://user-images.githubusercontent.com/3892806/41495453-97c05244-711f-11e8-8cbf-b1e4e51c3fd1.png)

**Comment by lcherone** [comment]
whats `uname -r` return? I may need to change the logic abit.

**Comment by lcherone** [comment]
No actually ignore that, re-login to the server, let me know if that fixes it?

**Comment by Meywether** [comment]
Yes completely deleting cache and cookies and the error went away. But after adding more users it does not work either. 
It seems that now the images server is down because I get and error in the image tab :+1: 
![image](https://user-images.githubusercontent.com/39849054/41500816-27e541be-7188-11e8-9036-a5aaea5a38ab.png)

**Comment by Meywether** [comment]
lxc info | grep "kernel_version: -> shows me : 

![image](https://user-images.githubusercontent.com/39849054/41500830-a03ce66c-7188-11e8-967c-bd60c287b5de.png)

**Comment by Meywether** [comment]
4.17 gets my linux not accepting any mouse events ^^ 
Can you try it with 4.16?

**Comment by lcherone** [comment]
I don't know what you mean. 

All I did was add a check on the kernel version, after brauner's coment on the version: https://github.com/lcherone/Conext/blob/master/.nuxt/components/lxd/devices/idmap.vue#L92

**Comment by Meywether** [comment]
Sorry about that.
I was just asking, if you can try if the user mapping limit is gone if you use a kernel > 4.15.

One of my problems was, that by using kernel version 4.17 within my virtualbox, my mouse were not working anymore.
