### ISSUE TITLE
<BUG> Internal Server Error Lib\Response not found

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#159]
Hi lcherone,
after installing Conext on a new server I got following error: (By using install sh script)

![image](https://user-images.githubusercontent.com/39849054/41584280-2e6fdfd2-73a7-11e8-8ff4-591db96d62fa.png)

Best regards
Meywether

****
Update: After trying another two times on different machines -> same issue 
Sorry ;)

**Comment by lcherone** [comment]
Sorry my bad, I moved something in the `config.ini` and broke the autoloader.

If you dont want to reinstall, open up the `config.ini` file and move 

; Framework
CACHE=true
DEBUG=0
AUTOLOAD=".api/"

above the [modules] section

so it be like:

```
[globals]

; Database
db.dsn="sqlite:./.plinker/database.db"
db.host=""
db.name=""
db.username=""
db.password=""
db.freeze=false
db.debug=false

; Enable/disable panel
PANEL.enabled=true
; If disabled, redirect, otherwise its 204 no content
PANEL.redirect=""

; path to lxc binary
LXC.path="/snap/bin"

; Auth Secret
AUTH.secret=""

; JWT
JWT.secret=""

; Framework
CACHE=true
DEBUG=0
AUTOLOAD=".api/"

; System Modules (remove items to remove features)
[modules]
server="network-connections","processes","logins"
api="data","email"
lxd="containers","images","operations","profiles","networks","devices","certificates","storage","ssh-keys"
routes="web","port"
tasks="user","system"

```

**Comment by lcherone** [comment]
@Meywether You have been a great help with this project, your definitely on my Christmas list :+1:

**Comment by Meywether** [comment]
Thanks a lot ;) 
Working again ;)
