### ISSUE TITLE
<Bug> Devices json: cannot unmarshal ...

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#162]
Hi lcherone,
it's me again ;)
Got following error in my container disk attachment:

![image](https://user-images.githubusercontent.com/39849054/41592746-e84dcf52-73bd-11e8-8032-f9fc7950e395.png)

my disk device looks like:
![image](https://user-images.githubusercontent.com/39849054/41592772-07852d84-73be-11e8-91a2-2acf4c3a9b6a.png)

Strangely, it worked before...

Best regards 
Meywether

****
Update: Even if I tick "optional" same error occurs

**Comment by lcherone** [comment]
Odd for some reason LXD wants the boolean values to be strings.. not sure how it worked before. I've added some code which will mutate the true/falses into strings when attaching.

**Comment by Meywether** [comment]
Check working, - Thaaaaanks!
You definitely earn the badge for the best issue response time! 
may you have seen this weird behavior inside the console (container console not ssh )  at your place?  
These line cropping is weird ;)

![image](https://user-images.githubusercontent.com/39849054/41593769-73242d6c-73c1-11e8-9bf7-b02a85131378.png)

**Comment by lcherone** [comment]
Not sure what that is, are you zooming? Mine is ok,  but also the font is slightly thinner (im using chrome, and looks the same in firefox too).

![screenshot-10 158 250 203-88-2018 06 19-12-08-56](https://user-images.githubusercontent.com/3892806/41593942-9b0015a6-73b9-11e8-9c81-7d83c22ce2bc.png)

**Comment by lcherone** [comment]
The lines are not what you would see in your normal console, e.g the new lines, how im doing it is on websocket message print as a string, it comes in from a Blob but can't figure out a way to output it correctly though websocket. The other way just ignores all line breaks and everything is broken, like if you did `top` it would scroll and be gibberish...

**Comment by Meywether** [comment]
ah ok, but it is not a really big issue for quick fixing something is enough !!

Thanks a lot ! cya ;)

**Comment by lcherone** [comment]
No worries, thanks for reporting.

**Comment by Meywether** [comment]
you are really welcome and thanks for you quick response  ##
