### ISSUE TITLE
Debugging question

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#167]
Hi lcherone,
i am still on the mapping problem regarding more than 5 users.
May it possible to get the sent lxc/lxd commands to be visible in the console for example.
Referencing issue: https://github.com/lxc/lxd/issues/3933#issuecomment-398684649
I want to find out where the mistake is, because there is anywhere a problem, but I can not figure it out.
For example the 1005 uid where the range is near a million ? WTF?
Or brauner said, that the ids are double mapped. (Do not know if this is a problem).

Thanks in advance!

**Comment by Meywether** [comment]
The funny this is:
if I map for example my user 1004 into the container the user 1005 gets also mapped and if I toggle 1005 I get this ( picture ) and then 1006 gets mapped into the container with the high gid.

![image](https://user-images.githubusercontent.com/39849054/41654595-3698e2e2-748a-11e8-870d-2fb19103a0e6.png)


Weird

Thanks in advance!
Meywether

**Comment by Meywether** [comment]
I am really near of the root of that problem, I can feel it. Its a kind of what first, what later problem. Ahh, Like in my angular projects or nodejs web apis, where I can really "smell" the bug ^^ XD

**Comment by lcherone** [comment]
Sorry late reply, busy day...

Ok, this is whats happing to me, I'm not sure its a bug or not with LXD but it's **not a bug in the panel** as I previously said all I'm doing is setting the value of `raw.idmap` with `both <UID> <UID>`, as suggested in the [documentation](https://github.com/lxc/lxd/blob/master/doc/userns-idmap.md#custom-idmaps). <sub>* though.. not a range, because it does not fit in with the logic of per-user toggling.</sub>

Coo so, if you add user 1000(ubuntu), then the panel will set `raw.idmap` to `raw.idmap=both 1000 1000`, and if you add another user say 1001, it will add the entry `raw.idmap="both 1000 1000\nboth 1001 1001"` and so on.

doing `lxc config edit ct1` would output the config as expected.

```
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180617)
 ...snip
 raw.idmap: |-
    both 1000 1000
    both 1001 1001
...snip
```

But in reality, whats outputted to the log is.

```
lxc.idmap = u 1000 1000 1
lxc.idmap = g 1000 1000 1
lxc.idmap = u 1001 1001 1
lxc.idmap = g 1001 1001 1
lxc.idmap = u 1002 1001002 999998998
lxc.idmap = g 1002 1001002 999998998
```

Which does not make sense `¯\_(ツ)_/¯` as nowhere apart from that log is it showing duplication.

Im not sure why its adding:

```
lxc.idmap = u 1002 1001002 999998998
lxc.idmap = g 1002 1001002 999998998
```

Something I noticed which you can try is all fails is just set the profile to privileged.

Again, all the panel is doing is updating the `raw.idmap` config value in the json, sending it up to the server and passing it to LXD, there is no voodoo going on in the background. https://github.com/lcherone/Conext/blob/master/.api/controller/api/lxd/containers/item.php#L205

Here is the dict that the API respondes with and the panel manipulates, sends up as a PUT and LXD then applys..

```
{
	"architecture": "x86_64",
	"config": {
		"image.architecture": "amd64",
		"image.description": "ubuntu 18.04 LTS amd64 (release) (20180617)",
		"image.label": "release",
		"image.os": "ubuntu",
		"image.release": "bionic",
		"image.serial": "20180617",
		"image.version": "18.04",
		"limits.cpu": "1",
		"limits.cpu.allowance": "50%",
		"limits.cpu.priority": "5",
		"limits.disk.priority": "5",
		"limits.memory": "1024MB",
		"limits.memory.enforce": "soft",
		"limits.memory.swap": "0",
		"limits.memory.swap.priority": "5",
		"limits.network.priority": "5",
		"limits.processes": "500",
		"raw.idmap": "both 1000 1000\nboth 1001 1001",
		"user.sshkeys": "",
		"volatile.base_image": "b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f",
		"volatile.eth0.hwaddr": "00:16:3e:99:38:4e",
		"volatile.eth0.name": "eth0",
		"volatile.idmap.base": "0",
		"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1001,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001002,\"Nsid\":1002,\"Maprange\":999998998}]",
		"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1001,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001002,\"Nsid\":1002,\"Maprange\":999998998}]",
		"volatile.last_state.power": "RUNNING"
	},
	"devices": [],
	"ephemeral": false,
	"profiles": [
		"default"
	],
	"stateful": false,
	"description": "",
	"created_at": "2018-06-20T17:31:16Z",
	"expanded_config": {
		"boot.autostart": "1",
		"image.architecture": "amd64",
		"image.description": "ubuntu 18.04 LTS amd64 (release) (20180617)",
		"image.label": "release",
		"image.os": "ubuntu",
		"image.release": "bionic",
		"image.serial": "20180617",
		"image.version": "18.04",
		"limits.cpu": "1",
		"limits.cpu.allowance": "50%",
		"limits.cpu.priority": "5",
		"limits.disk.priority": "5",
		"limits.memory": "1024MB",
		"limits.memory.enforce": "soft",
		"limits.memory.swap": "0",
		"limits.memory.swap.priority": "5",
		"limits.network.priority": "5",
		"limits.processes": "500",
		"raw.idmap": "both 1000 1000\nboth 1001 1001",
		"security.nesting": "0",
		"security.privileged": "0",
		"user.sshkeys": "",
		"volatile.base_image": "b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f",
		"volatile.eth0.hwaddr": "00:16:3e:99:38:4e",
		"volatile.eth0.name": "eth0",
		"volatile.idmap.base": "0",
		"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1001,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001002,\"Nsid\":1002,\"Maprange\":999998998}]",
		"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1001,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001002,\"Nsid\":1002,\"Maprange\":999998998}]",
		"volatile.last_state.power": "RUNNING"
	},
	"expanded_devices": {
		"eth0": {
			"nictype": "bridged",
			"parent": "lxdbr0",
			"type": "nic"
		},
		"root": {
			"path": "\/",
			"pool": "default",
			"type": "disk"
		}
	},
	"name": "fff",
	"status": "Running",
	"status_code": 103,
	"last_used_at": "2018-06-20T18:01:21Z",
	"location": "",
	"state": {
		"status": "Running",
		"status_code": 103,
		"disk": [],
		"memory": {
			"usage": 47001600,
			"usage_peak": 78028800,
			"swap_usage": 0,
			"swap_usage_peak": 0
		},
		"network": {
			"eth0": {
				"addresses": [{
						"family": "inet",
						"address": "10.0.0.23",
						"netmask": "24",
						"scope": "global"
					},
					{
						"family": "inet6",
						"address": "fe80::216:3eff:fe99:384e",
						"netmask": "64",
						"scope": "link"
					}
				],
				"counters": {
					"bytes_received": 314506,
					"bytes_sent": 11970,
					"packets_received": 288,
					"packets_sent": 146
				},
				"hwaddr": "00:16:3e:99:38:4e",
				"host_name": "vethIPS4CT",
				"mtu": 1500,
				"state": "up",
				"type": "broadcast"
			},
			"lo": {
				"addresses": [{
						"family": "inet",
						"address": "127.0.0.1",
						"netmask": "8",
						"scope": "local"
					},
					{
						"family": "inet6",
						"address": "::1",
						"netmask": "128",
						"scope": "local"
					}
				],
				"counters": {
					"bytes_received": 1027,
					"bytes_sent": 1027,
					"packets_received": 15,
					"packets_sent": 15
				},
				"hwaddr": "",
				"host_name": "",
				"mtu": 65536,
				"state": "up",
				"type": "loopback"
			}
		},
		"pid": 10308,
		"processes": 30,
		"cpu": {
			"usage": 4218691694
		}
	},
	"snapshots": []
}
```

**Comment by Meywether** [comment]
I will try and get it ;) Thanks a lot °

**Comment by Meywether** [comment]
And do not worry about the reply. I know how stressful some weird days can be !
Cheers ;)

**Comment by lcherone** [comment]
Whilst I was testing for the issue, I had the default profile privileged, and mapping was not showing anything in the log..and the mapping was working perfectly with a mounted disk device.. took me a while to understand why it was working when no mapping was happening.. lol

So if your trying to bind alot back to the host, using a privileged profile is always an option if everything else fails or feels convoluted.

**Comment by Meywether** [comment]
I had the time to test the mapping with two containers and had to mention this:

Mapping up to five ok -> then start container -> works
Stopping, -> Mapping five to ten again -> works

I could reproduce it one more time, but I want to check ist a third time.
Funny thing, after mapping, touching a file inside the container, the file on the host was insise a debian-tor group, whatever that is ^^

See ya :)

PS: Yeah gonna try priviledged!

**Comment by Meywether** [comment]
Can be closed, solved by a "weird" workaround as mentioned by me in https://github.com/lxc/lxd/issues/3933#issuecomment-399180362

Thanks a lot !
Best regards
Meywether
