### ISSUE TITLE
<Bug?> broken pipe in install sh?

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#169]
Hi lcherone;
after installing by your script, I get following at the end.

![image](https://user-images.githubusercontent.com/39849054/41665097-71ab50a0-74a7-11e8-8c36-b7db1f9bec4b.png)

But the project seems to work!

Best regards
Meywether

**Comment by lcherone** [comment]
I'm using `</dev/urandom tr -dc "$(date +%s%N | base64 | head -c 64 ; echo)$chars" | head -c64; echo ""` to gen secrets, urandom may of hung abit before hitting the end of the script.

Did the secrets generate ok? check the `config.ini` if so ignore it.

**Comment by Meywether** [comment]
Yeah login works, but I got an error in the ssh key section, pasting a valid ssh key resulted in -> could not be stored in database (or similar, not at home now)

**Comment by Meywether** [comment]
Yeah, I will do it tomorrow morning, just after getting to my laptop around 8 am. It was an clean install but got stuck one team before snap lxd command runs, because something broke my internet and I had to run it manually again. 
Maybe think about removing any previous lcx symlinks. Sometimes, if the install broke just after setting the symlink, it really gets a struggle to get of the errors. Symlink here and symlink there. Maybe get a check if the path would fit leave it otherwise delete and retouch the link.

Good night, thanks a lot again!
See ya!
Best regards 
Meywether

**Comment by Meywether** [comment]
Whoops type in title -> sorry!

Here my config 

`root@ubuntu1804test:/home/operations# cat /var/www/html/config.ini
[globals]

; Database
db.dsn="sqlite:./.plinker/database.db"
db.host=""
db.name=""
db.username=""
db.password=""
db.freeze=false
db.debug=false

; Enable/disable panel
PANEL.enabled=true
; If disabled, redirect, otherwise its 204 no content
PANEL.redirect=""

; path to lxc binary
LXC.path="/snap/bin"

; Auth Secret
AUTH.secret="HvnpJ,uE$hOGLVs)>5g]Skb%R=praK/i"

; JWT
JWT.secret="8A-Mq2A;B78Pd{_PJG2twE@<G9}{;-TQc_QlV)CIW9NSUVve4}KywmqqK$z]+&5]"

; Framework
CACHE=true
DEBUG=0
AUTOLOAD=".api/"

; System Modules (remove items to remove features)
[modules]
server="network-connections","processes","logins"
api="data","email"
lxd="containers","images","operations","profiles","networks","devices","certificates","storage","ssh-keys"
routes="web","port"
tasks="user","system"

`

**Comment by Meywether** [comment]
FYI thats the correct error message: (also after git pull today) 

![image](https://user-images.githubusercontent.com/39849054/41700881-798e6626-752a-11e8-806c-49c1100293cd.png)

**Comment by lcherone** [comment]
Seems ok, 

Can you run.

`chown www-data:www-data /var/www/html -R`

and check the database is there `.plinker/database.db`

You might need to move over the initial one if its 0 bytes.

`cp /var/www/html/.api/files/database.db /var/www/html/.plinker/database.db && chown www-data:www-data /var/www/html/.api/files/database.db && chmod 0644 /var/www/html/.api/files/database.db`

**Comment by Meywether** [comment]
> chown www-data:www-data /var/www/html -R

that was the first try I did -> same result

database is there:
![image](https://user-images.githubusercontent.com/39849054/41702027-e97925da-752e-11e8-8d4d-91999f9fcd06.png)

after executing you command the database file was increased in its file size but it resulted in the same error!
Sorry XD

**Comment by lcherone** [comment]
I just checked the code and it was a bug which crept in when I did the refactoring, I've fixed it you should be able to do git pull and it will work.

**Comment by Meywether** [comment]
confirmed! 
working again!
Thanks a lot lawrence!

**Comment by lcherone** [comment]
no worries thanks for reporting it :+1:

**Comment by Meywether** [comment]
👍
