### ISSUE TITLE
<Bug> Starting container from own image resulting in validate error

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#173]
Hi lcherone,
caught another one: 
![image](https://user-images.githubusercontent.com/39849054/41735432-f4252046-7589-11e8-8906-790b574f7ea3.png)

I made an image from an container and wanted to relaunch them, but the launch button did not work!
See the console, some kind of validation error!

Best regards
Meywether

**Comment by lcherone** [comment]
Yeah the form validation ref conflicts if you open diff modals, i've changed it so they all got diff refs now. Should be able to git pull it be fixed

**Comment by Meywether** [comment]
Thx! confirmed Working again!.
Puhh, I am throwing something in the "room" to discuss.
Do you think it is possible to not just copy the container image itself but also the settings, device ...?
Best regards
Meywether

**Comment by lcherone** [comment]
Images don't have settings/profiles or devices.
 
Do you mean a way to copy settings and devices to other servers?  It's possible as I could use rpc, though knowing whats attached to-what-not and attaching it back is not, as the system doesn't keep track of whats attached/set on the containers.

**Comment by lcherone** [comment]
I think using remote profiles is possible with LXD but not tested it. nor whether it works with profiles with devices, dunno..

**Comment by Meywether** [comment]
Yeah I see ! Ok thanks ! 
Best regards
Meywether :)
