### ISSUE TITLE
Add Copy and Move to list of functions in "Container Actions"

### ISSUE THREAD

**Issue by bmullan** [lcherone/Conext#21]
I use Ubuntu 18.04, SNAP LXD

In the Container tab I can see my Containers on that server.
Selecting one of the containers and clicking on "Container Actions" just shows current Actions limited to: 

- Console, 
- Stop, 
- Freeze, 
- Restart, 
- Snapshot

I would like to recommend implementation and addition of these as Action Items:

- Copy (re lxc cp cn1 cn2) useful for cloning. 
- Move (re lxc mv cn1 cn2), 
- and possibly  an "Action" which would initiate an "lxc info cn1" where cn1 is a container name.   This  would show all current info about cn1 (cpu, memory, network activity)

Just thought I'd post for comments.

**Comment by lcherone** [comment]
Ill look into adding them.. in the meantime, you can move containers, by adding the remote via cli, creating an image from a container and then logging into the other server and creating a container from that image, though your right it would be nice to just be able to click a button.

:/ cpu, memory, network activity, processes (just added) are displayed in the table already, some info like all the network ips, disks (going to add this) and pid are missing, was going to add them as extra info on clicking the value in the table..

**Comment by bmullan** [comment]
Thanks... Sounds good.

**Comment by lcherone** [comment]
Not in latest release yet, but I've added copy images between remotes. Ill use the same method for containers so shouldn't be an issue.
Stay tuned...

**Comment by bmullan** [comment]
you want to be able to copy locally or remotely

- lxc copy cn1 cn2                                             # copy cn1 to cn2  
- lxc copy remotehost1:cn1 cn1                        # copy cn1 from remotehost1 to cn1 locally  
- lxc copy cn1 remotehost1:cn5                        # copy cn1 to remotehost1 and name it cn5

**Comment by lcherone** [comment]
From local to local and local to remote I've done, ill add the choice of name (currently it just appends -copy to the end)

From remote to local can be achieved by logging into the server with the container you want to push/copy to a remote and then do it that way.. else a UI will need to be made for listing remotes containers..

**Comment by lcherone** [comment]
- Added choice of different name when copied.
