### ISSUE TITLE
If local LXC can talk to local -or- remote LXD Daemon's shouldn't Conext be able to?

### ISSUE THREAD

**Issue by bmullan** [lcherone/Conext#22]
Per LXD CLI Getting Started:
https://linuxcontainers.org/lxd/getting-started-cli/

In section titled **Multiple Hosts**

> The "lxc" command line tool can talk to multiple LXD servers and defaults to talking to the local one.

I believe the API also supports querying the local LXD Daemon for other LXD machines it "knows" about.

Wouldn't Conext be able to do the same, using the API, connect to the _remote_ LXD daemon & manage the LXD containers running on that "host" ?

**Comment by bmullan** [comment]
I found an example of this on github...

[PlinkerRPC - LXD](https://github.com/plinker-rpc/lxd)

> Control LXD through RPC which uses the local instance of LXD and lxc query to manage local or remote LXD servers.

**Comment by lcherone** [comment]
I'm not sure what you mean, it can.. This project uses PlinkerRPC exclusively .. :/ which is my lib. The credentials you add when adding a server are the RPC connection details to the server, if you want to talk to another server from the server, you can by using a task or making an API endpoint (which there is an example already).. 

No there is no API endpoint for remotes. https://discuss.linuxcontainers.org/t/manage-remotes-via-api/1585

Whats expected, to talk to multiple hosts you need to keep track of the host's locations and LXD secrets and then generate and add the PEM certs to the host you want to connect to using the `/certificates` endpoint. Like the majority of LXD client libs do. Ones that don't have issues with fiddling with PEMs in the browser, which is a pain.

**Comment by lcherone** [comment]
Remeber this project is only 17 days old ;p

**Comment by bmullan** [comment]
Lawrence...    don't take my comments wrong I'm just trying to help make
Conext more full.   No one can think of everything right?    Anyway some of
what write is often related to how new I am to using Conext also.

Great job so far tho'

Brian

**Comment by lcherone** [comment]
No its all good, I appreciate your input and suggestions :)
