### ISSUE TITLE
Add Networks

### ISSUE THREAD

**Issue by lcherone** [lcherone/Conext#23]
Add ability to manage networks, (ip4/ip6 bridges).

**Comment by KathrynMorgan** [comment]
As part of the feature request, it would be great to have toggles for available networks on container/profile actions to enable/disable specific networks per-container && per profile

**Comment by lcherone** [comment]
Almost done.. going to have think about how this will fit with the `iptables.build` task, as port forwarding will be confusing if the container has multiple bridges.

For now, it would be upto the user to change the built task with the correct bridge they want to forward, if not lxdbr0, and it applies to all containers.

**Comment by lcherone** [comment]
Management part done..

![screenshot-10 158 250 203-3000-2018 06 03-20-51-27](https://user-images.githubusercontent.com/3892806/40890556-ebc671a2-676f-11e8-8c84-54748d8c450d.png)

**Comment by KathrynMorgan** [comment]
Wow, good progress! I personally use the openvswitch driver and remove all lxd network control. Is there a straight forward way to disable Nat/dhcp ?

**Comment by lcherone** [comment]
Ill add it, im following https://github.com/lxc/lxd/blob/master/doc/networks.md for the options, not sure how they all fit/work together..

So if I add the option for  `bridge.driver` to toggle between `native` and `openvswitch`, what options should I leave out?

The toggles on the side of IPv4 DHCP disable/enable it and it removes the section, for the NAT its just that toggle.

Though im using the PUT request, it's not actually replacing the config, PATCH does the same :/ lol, https://github.com/lxc/lxd/blob/master/doc/rest-api.md#put-etag-supported-6 so im having a few issues removing the items once set. Though testing it for example if `ipv4.dhcp = false` the ipv4.dhcp.* keys are not conflicting.
Happy dayz..

**Comment by KathrynMorgan** [comment]
I'm doing family stuff now but can come online in about 5 hours to see what I can dig up and share more about the difference between ovs and native drivers. I really like this project though.

**Comment by lcherone** [comment]
Devices section added, defined nic's which can be attached/detached to per-containers. Still need to add to profiles, which ill do after adding the blocker device else it will cause some confusion.

Figured out why PUT didn't work, as an empty array for profiles `[]` is ok but devices is an empty object `{}` and is ignored if not an object, but json_encode turns `{}` into `[]`, and json force object turns array's into {"0": 'foo'} so breaks profiles lol but its working now.

**Comment by KathrynMorgan** [comment]
Okay on the topic of native or ovs, all other key values that i've interacted with work as well but the ovs dependency needs to be met with an active openvswitch-switch.service as well so some sanity check would be required to allow it.

**Comment by lcherone** [comment]
Cool, guess ill leave that to the user, they will know if they setup openvswitch.. 

I just added disks to devices which works nice but going to get non LXD users inquire about uid/gid mappings in accessing the mount. ¯\_(ツ)_/¯  lol

**Comment by bmullan** [comment]
On the LXD subreddit was a link to LXD/OVS use:

http://www.francescoprovino.com/2018/04/27/network-management-with-lxd-and-openvswitch-in-ubuntu-18-04/

Don't know if any of it is helpful to you or not

**Comment by KathrynMorgan** [comment]
@bmullan that write up has decent OVS usage but some of his warnings have straightforward workarounds and what he presents there is a partial picture of OVS usage.

If that article raises any questions i'll be happy to elaborate on OVS usage

**Comment by bmullan** [comment]
Kat

Thx...  I'm not a coder but was involved with a lot of sdn, vxlan, ovs,
opendaylight etc before I retired from Cisco 3 yrs ago.

I just saw Conext is now adding some LXD/OVS integration so I thought I
might pass on some lxdbovs related posts I'd come across so anything useful
can be helpful.

I might have a couple more coming ;-)

Brian
