### ISSUE TITLE
Click on LXD then Network then my LXD Bridge name & red-box error "e.editingItem.config is undefined"

### ISSUE THREAD

**Issue by bmullan** [lcherone/Conext#28]
Fresh Ubuntu 18.04 VM
Installed Conext this morning using Install steps.
Created a test container called CN1
everything looks ok in Conext.

In Conext I Click on:

- LXD then
- Networks then
- click on my LXDBR0 and 

I get a red box with an "!" exclamation mark and under the ! it says:

_e.editingItem.config is undefined_

**Comment by lcherone** [comment]
By the sound of it, it's most likely breaking on https://github.com/lcherone/Conext/blob/d8cb1cb32d4f820d2917d0c66598897cebfd929b/.nuxt/pages/lxd/networks.vue#L307

For some reason the config is not set on that network, which is weird, from what I see its sometimes empty but its set. I've done a few changes to the networks part, so It might be fixed, but ill add another check in.
