### ISSUE TITLE
Manage Storage

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#43]
Hi there,
really well done work you provided for us lcherone! Really nice! Thanks a lot

My question is about storage pools.
I was not able to figure out how to manage them, create them or assigning a profile or a container to a certain storage pool!

Am I blind?
Thanks in advance!!
Best regards
Meywether

**Comment by lcherone** [comment]
You're not blind, it's not added yet, ill put it on the todo list.

**Comment by Meywether** [comment]
Thanks for your response lcherone!!
Yeah would be really nice! Please consider to add also the functionality for creating storage pools at custom places e.g. on two different ssds.

Thanks in advance !!! 

Best regards 
Meywether

**Comment by lcherone** [comment]
@Meywether added initial storage feature. I still need to add the per-volume config part.

I've not tested with all the storage types as im developing the project in a container, the errors when attempting to do something lead me to think im entering stuff wrong but would work, so a more experienced user needs to let me know what needs changing. dir's working fine ;p

Let me know any issues you can see, I tend to just stick with the `default` pool and not mess with storage in my setups.

**Comment by lcherone** [comment]
Note the usage bar, will show values in it, just waiting for a merge in vuetify to happen: https://github.com/vuetifyjs/vuetify/pull/4106

**Comment by Ragitagha** [comment]
Great thanks a lot! - I gonna test it!

Ok, thanks lcherone. The storage creation at custom locations works very well!

So a more general question do you know how to mount home folders of different users to a container and each one can only write to his specific dir? I did not figured it out with user mapping, that would be a great feature to automate this .

Steps would be:
Add User Y in group Z and create a mount with mapped UIDs into a container. 

Mmh whyever i always get an error if I try to mount a disk within a container :  Storage volumes cannot be specified as absolute paths. 

Something I did not get.

**Comment by Meywether** [comment]
Great thanks a lot! - I gonna test it!

Ok, thanks lcherone. The storage creation at custom locations works very well!

So a more general question do you know how to mount home folders of different users to a container and each one can only write to his specific dir? I did not figured it out with user mapping, that would be a great feature to automate this .

Steps would be:
Add User Y in group Z and create a mount with mapped UIDs into a container.

Mmh whyever i always get an error if I try to mount a disk within a container : Storage volumes cannot be specified as absolute paths.

Something I did not get.

Do you have an idea?

Best regards
Meywether

**Comment by lcherone** [comment]
I'm not 100%.. I think you add it as a disk device and then fix the uid/gid manually. 

Whilst doing the devices -> disks feature it added the device but you have issues with nobody/nogroup.. and though the api setting the `raw.idmap` value did not fix it, I couldn't figure it out so I removed it,

https://github.com/lcherone/Conext/blob/master/.nuxt/components/lxd/devices/disk.vue#L227 

Don't really wont to go down the route of allowing www-data to write to `/etc/subuid` etc, sudo access to lxc binary should be enough if things aren't possible without doing directly through the API or with just `lxc` cmd then it needs to be done by the user.

So the user would need to remedy it themselves. Plenty of tuts on the subject: https://tribaal.io/nicer-mounting-home-in-lxd.html

**Comment by Ragitagha** [comment]
> Don't really want to go down the route of allowing www-data to write to /etc/subuid etc, sudo access to lxc binary should be enough if things aren't possible without doing directly through the API or with just lxc cmd then it needs to be done by the user.

Yeah I agree with you. 

The problem with your suggest site is that after following it the config of the container breaks and it won't restart again.

**Comment by Meywether** [comment]
>Don't really want to go down the route of allowing www-data to write to /etc/subuid etc, sudo access to lxc binary should be enough if things aren't possible without doing directly through the API or with just lxc cmd then it needs to be done by the user.


Yeah I agree with you.

The problem with your suggest site is that after following it the config of the container breaks and it won't restart again.

**Comment by lcherone** [comment]
@Meywether Just been playing around with devices->disks, got `Storage volumes cannot be specified as absolute paths.` when set the source to a path.. If you use a pool it should be the name of the pool.

For example:

Create a storage pool, then create a disk device and select the pool..

![screenshot-10 158 250 203-3000-2018 06 09-22-59-13](https://user-images.githubusercontent.com/3892806/41196480-ede146f6-6c38-11e8-8fc7-5ee8cda10889.png)

then attach the device to the container.

![screenshot-10 158 250 203-3000-2018 06 09-23-01-16](https://user-images.githubusercontent.com/3892806/41196487-192695dc-6c39-11e8-85c4-93404abbb0e4.png)

Win..

![screenshot_2018-06-09_23-03-01](https://user-images.githubusercontent.com/3892806/41196494-49d0ddc8-6c39-11e8-8152-61090e1994c1.png)

LXD's great.. nested desktop env container in a container, with a proxy through them both into VNC.. 

![screenshot-10 158 250 203-3000-2018 06 09-23-05-58](https://user-images.githubusercontent.com/3892806/41196511-b819c8b2-6c39-11e8-935a-f88a10ffb551.png)

**Comment by lcherone** [comment]
Added ability to manage uid/gid id mapping to containers, so just have to setup which user you want to map on the host and then toggle it on and off in the UI

So for example, map `ubuntu` on the host to `ubuntu` in the container, so the containers ubuntu user  can read/write to `/home/ubuntu` on the host... which you setup as a `disk` device, same would apply for any user/folder as requested.

**So run on host:**

`echo 'ubuntu:1000:1' | sudo tee -a /etc/subuid /etc/subgid`

Then in the UI toggle the user (all users and associated ids are fetched from the host).. and it does equivalent to: `echo -en "both 1000 1000" | lxc config set test raw.idmap -`

![screenshot-10 158 250 203-3000-2018 06 10-06-46-08](https://user-images.githubusercontent.com/3892806/41198617-ff25e85e-6c79-11e8-8812-a72f114a8db8.png)

Note, just toggling them all or not mapping the user will prevent the container from starting until unmapped.

**Comment by Meywether** [comment]
Hi lcherone,
just one sentence to wrap it up: You are great! 

Just found one thing within your installation script. 
Trying to ping the google DNS for checking internet connections is fine but most environements where I wanna use it filter ping attempts by default.
I suggest to make a http request via Port 80 or 443 because these ports are - hopefully - never been blocked.  Or try ping first and after 10 attempts try a http request for google.com and if 200 returned everything is fine. I love your installation script it is clean and well commented!

About popxy devices: They are working but I ran into another issue while connecting via ssh into a container: Using putty and mobaXterm,

> No supported authentication methods available (server sent: publickey)

Whyever, passwd is set correctly and I need for some users normal password login. 
Are proxy's set to autostart `?

At uid mapping just a question:

I tried your suggestion:

> So for example, map ubuntu on the host to ubuntu in the container, so the containers ubuntu user can read/write to /home/ubuntu on the host... which you setup as a disk device, same would apply for any user/folder as requested.

I have following done:

![image](https://user-images.githubusercontent.com/39849054/41200656-4e17f8e2-6ca9-11e8-8084-98052cfe4298.png)

resulting in: 

![image](https://user-images.githubusercontent.com/39849054/41200661-6815fc3a-6ca9-11e8-91c8-0bf1776e9803.png)

I have this example setting:

Host: User are known:

Test1
Test2
Test3

Container Users are known:

Test1
Test2
Test3

Question as expected:
Can I mount their home dirs? 

from host/home/test1...
to container/home/test1 

expecting test1 @ container can RWX to the mounted dir.
Do I have to create a storage pool for each user? Because I ran into the same issue:

![image](https://user-images.githubusercontent.com/39849054/41200668-a2e2a0c0-6ca9-11e8-8299-9db42754e22e.png)




Concerning mounting pools as disks: 

Following setting: 
Storage:

![image](https://user-images.githubusercontent.com/39849054/41200705-1b8711be-6caa-11e8-9d01-bbdd12dd67b4.png)



Disk:
![image](https://user-images.githubusercontent.com/39849054/41200702-0629c71c-6caa-11e8-87b8-e763040b833b.png)

Resulting in: as expected:
![image](https://user-images.githubusercontent.com/39849054/41200696-f0b4cefe-6ca9-11e8-8787-c3eb1850e783.png)

But no visible devices within the container.

Sorry to annoy you with this!

One another thing I was not thinking about for, is: What would be the safest way to update your project? Just running you installation script again could break my containers. 

Thanks in advance!!!

Best regards
Meywether

**Comment by Meywether** [comment]
Hi lcherone,

After several hours testing I figured out the error:
![image](https://user-images.githubusercontent.com/39849054/41202841-44fbec3e-6ccf-11e8-87d9-577547015766.png)

Although the pool is configured. 

![image](https://user-images.githubusercontent.com/39849054/41202844-5f53b6fc-6ccf-11e8-8d15-6c1a14e5f1a4.png)

I really do not know where my mistake is placed.
If you want, I can share a screen video to you setting it all up. Please provide me an email or messenger id!

Best regdards
Meywether

**Comment by lcherone** [comment]
I'll try answer some of your questions.

 - Pinging google - I did this so people would install on a machine which has internet, as it would fail without it, plus I develop in containers and waiting for the network interface and DHCP to issue an ip can be a bit slow. Ill prob removes it altogether. You could always just fork the install script and use your own custom one, the idea was that you could do that and install additional stuff if you needed, the main installer which sets up the script presumes the system has internet so it wouldn't break.

 - About proxy devices - When you create a web forward its placed in a sqlite database on the host and then worked through by the `*.build` tasks... iptables.build for port forwarding and nginx.build for web forwarding. But you must have the task setup to be running or it wont build, you can see from the tasks that the number increments if it's not running it won't. Which could be an issue with the cronjob. 

Note when using domains for Lets Encrypt they MUST be pointing to the server before attempting to do the SSL! So set it up first as normal HTTP, check it if it works then toggle SSL, doing it before without checking will cause LetsEncrypt to fail and you might be blocked for creating certs for a while.

If you are on about the `LXD->devices->proxy`.. this is done by LXD.. Which I actually prefer now its implemented.. so I may remove the Routes -> Port Forwards in future and remove all the tasks etc, as it works well.

Ok with the disks, the first images you are using a **pool**.. If you want to mount the host home dir then choose none for the pool.

Its difficult to make it easy to understand as the disk devices are meant to handle both mounting host dirs, disks and pools.. not all options apply for all.. The original image I showed at the top is how you do it.. Source `/home/user1` path `/home/user1`.. no pools.. then it will work..

With the other stuff just looks like you were trying to make volumes and mount the.. to mount a file from the host to the container "storage" is not involved.

The operations entries, pilling up.. When you open the console for the container via the UI a websocket connection is made to the host into the container, that stays open until you restart the container, its normal behaviour. tbh the list can get pretty large when moving images and containers etc, some can be cancelled some not.. but basically, they all clear when the container or host is restarted. 


Hopefully, that covers it, Im glad you like the system, thanks..

**Comment by lcherone** [comment]
Sorry looking at the image above I was using a pool..

So it would be like the following but you MUST have them folders and users created on both the container and the host.

![screenshot-10 158 250 203-88-2018 06 10-21-49-36](https://user-images.githubusercontent.com/3892806/41206190-590bacc2-6cf8-11e8-8da5-071788de875a.png)

**Comment by lcherone** [comment]
Added so if you choose a pool it set the source.

**Comment by lcherone** [comment]
- Added attach/choose storage pool to profile. 

Closing the issue as the feature is implemented now. If you have any other probs open a new issue.
