### ISSUE TITLE
Failed to connect to host, check details

### ISSUE THREAD

**Issue by bmullan** [lcherone/Conext#5]
I downloaded the latest code
installed it
followed your instructions (note correction of path to lxc for snap is /snap/bin/lxc)
edited sudoers
rebooted
tried to access from host and get the web interface

Clicked Add a Server
used "secret" I was given after installation
use Label "host1"
saved

click on that "host1" and get an error:

**Failed to connect to host, check details.** 

I am using SNAP LXD and I know its working because I can manually create a new container.

**Comment by lcherone** [comment]
Did you add it as `http://IP:88` note port `88`

If the secret is wrong you would get `invalid secret`. Failed to connect to host, check details, is when the host is wrong and it cant access the host.

If you used the github hosted panel, then you need to allow insecure scripts.. (well its because github uses HTTPS and the panel wont).

**Comment by bmullan** [comment]
> Did you add it as http://IP:88 note port 88

My host IP is 192.168.122.128 so the command I used:

http://192.168.122.128:88

That brings up the menu.

Clicked ADD SERVER

filled in the form with:

Label:  host1
Host:  192.168.122.128
Secret:  the secret key shown to me by installer.sh script.

Click Save.

Click on that Host and get the above error in orig post.

**Comment by bmullan** [comment]
I guess while I'm asking questions _"where"_ would I _"check details"_ (see orig error msg) if I actually wanted to _"check details"_?

**Comment by lcherone** [comment]
The details are the item.

You should enter as:

Label: host1
Host: http://192.168.122.128:88
Secret: the secret key shown to me by installer.sh script.

Notice the `http://` and the `88`

**So like:**

![screenshot](https://user-images.githubusercontent.com/3892806/40849993-5e80de6e-65bb-11e8-8061-6b32a5974bdf.png)

Hopefully, that helps.. I've changed the servers page a bit so it does a quick get request to the url and sees if it can connect and shows a status column.

**Comment by lcherone** [comment]
Also heres a screen:

<img src="https://camo.githubusercontent.com/3baaa5a6c62abc99eed92ee1b558e9ee1e0b34ed/68747470733a2f2f692e696d6775722e636f6d2f513145304f55372e676966">

**Comment by bmullan** [comment]
might be a good idea to note that IP:88 has the HOST IP as well.   You
mention it when telling the "user" how to connect to the web interface but
in that Edit Server box it just asked for "Host"
 & doesn't mention requirement to append the ":88" also

Lastly, from an "end-user" perspective.. shouldn't the software take care
of the prepend of the "*http://*" and append the "*:88" so all the end-user
has to do is enter IP address of the Host* ?


thanks
brian

**Comment by lcherone** [comment]
Ive just added some validation, which makes it more clear.

![screen](https://user-images.githubusercontent.com/3892806/40850899-b7ffe4d8-65bd-11e8-93c8-df189edb8905.png)

No can append it as the idea is you can change the ports in nginx.build task or use a reverse proxy in front so it could be https://panel.domain.com, also hosts like AWS provide domains etc.

**Comment by bmullan** [comment]
I can now click on my Host and get a display with CPU, Memory and Disk.

But there are no values presented.

I click on Server and everything is 0 (zero) ?

There also are no network connections listed ?

Clicking on Logins and it says "no data available"

Suggestions what I missed in configuring ?

**Comment by lcherone** [comment]
Whats the browser console show?

**Comment by bmullan** [comment]
firefox's "console" has 8 tabs:

inspector
console
debugger
style editor
performance
memory
network
storage

If I click on the "console" tab it doesn't show anything.

or are you refering to some other "browser console" ?

**Comment by lcherone** [comment]
you want to look at the network tab, the urls will show as 

 - /api/server/information/cpu
 - /api/server/information/memory
 - /api/server/information/disks

Click on them and find the response tab, and it should look like:

```
{
    "error": null,
    "code": 200,
    "data": {
        "memory_stats": {
            "used": 5.0,
            "cache": 6.0,
            "free": 89.0
        },
        "memory_total": "16167896"
    }
}
```

If not then post what it shows.

**Comment by lcherone** [comment]
Hopefully, you didn't download the version after I removed getallheaders function... :s

**Comment by bmullan** [comment]
In my network tab I just get "no data available" in your gui window

**Comment by lcherone** [comment]
refresh the page after you opened the console

**Comment by bmullan** [comment]
I just installed on a fresh ubuntu 18.04 server using your github "With
Install.sh Script" instructions?

**Comment by bmullan** [comment]
I did that and the firefox Browser Console is just blank

**Comment by lcherone** [comment]
I've just tested it on ubuntu 18.04 from the script, and its working fine:

![ubuntu 18 04](https://user-images.githubusercontent.com/3892806/40852842-d79063f8-65c3-11e8-8179-616c56227168.gif)

**Comment by bmullan** [comment]
Okay...

I'll start another vm up and reinstall using the script again and see what
happens.

Brian

**Comment by bmullan** [comment]
Just created a new Ubuntu 18.04 VM

Installed SNAP LXD

Used your latest Setup.sh script:

With Install.sh Script

> On a clean Ubuntu server run the following commands to install the system from a gist, or see further down on how to do it manually:
> 
> # switch into root user!
> sudo su
> 
> # update package lists
> apt update
> 
> # install wget
> apt install wget
> 
> wget https://gist.githubusercontent.com/lcherone/d7e5ba660bc20d738132ccb1a453459d/raw/cf389b1a0d7f988a2987f8f5ae7b88ad267f0d99/install.sh && bash install.sh
> 
> Once complete, you will be able to go to the panel at http://IP:88, and then add the server, with the provided key during install.

Now when I go to:   http://my-ip:88

I get a red box on the screen that says:
**this.loggedUser.mod.server.includes is not a function**

that's before I see the normal ADD A SERVER type screens it just goes straight to that red box w/that msg.

**Comment by lcherone** [comment]
Should work in chrome, are you using an old version of firefox?

The includes function is supported in over version 43: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by lcherone** [comment]
one thing it could be is if the same host (you reimaged the vm).. and upon hitting the panel again it was still logged in and then its picked up the old array from localStorage.. if thats the case just clear your cache.

I've made changes today which was not in yesterdays version, so you can define what features you want in the config.ini, incase you were to not need the api or tasks features etc.

**Comment by bmullan** [comment]
No it's latest firfox v60

**Comment by bmullan** [comment]
Ok I got it working.

Before when I ran your script install.sh I had always already had SNAP LXD configured.

In a new Ubuntu 18.04 VM I made sure both the SNAP LXD and the regular LXD were uninstalled prior to running your script and it worked.

Brian

**Comment by bmullan** [comment]
Connect now sees containers I create manually from the cli. Does your tool all for creation of lxd containers ?  Or is it for just managing existing servers & containers?

Thanks
Brian

**Comment by lcherone** [comment]
I'm not sure I understand.. Its a panel to manage LXD servers, it will see the containers you make with the cli and you can make containers from the images page, if you add a remote to lxd it will see the remote in the images page.
