### ISSUE TITLE
passwd error in container

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#76]
Hi lcherone,
after successfully mapping UIDs into my container and sharing home dirs, I wanted to add a new user and ran into following issue the same appears if I want to change a password:

![image](https://user-images.githubusercontent.com/39849054/41219475-ef3f25a2-6d4d-11e8-8e75-6e110bd439db.png)
______
My setting:

![image](https://user-images.githubusercontent.com/39849054/41219624-6905c8be-6d4e-11e8-99cb-eda2f1e4eb01.png)

Thanks in advance!
Best regards Meywether

**Comment by lcherone** [comment]
This is not related to the control panel.
