### ISSUE TITLE
Bug network page error e.editing.used_by is undefined

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#81]
Hi lcherone,
**Describe the bug**

undefined error in network page

**To Reproduce**

Steps to reproduce the behaviour:
I want to edit an already existing network device and click on the link.

**Expected behaviour**

Page where I can edit network bridgfe settings

**Screenshots**

![image](https://user-images.githubusercontent.com/39849054/41227104-392cf13e-6d63-11e8-8b0b-f31e379e39fa.png)

Thanks in advance
Meywether

**Comment by lcherone** [comment]
Nice catch, I did not test with networks created with cli, had a bug that if `bridge.mode` was not set it overwrote the whole object. Sorted now in the v0.1.36 release.

**Comment by Meywether** [comment]
You are  welcome.
Can you tell me how to safely update the project with running containers?

**Comment by lcherone** [comment]
At this stage, installing with git is the best way as im doing many updates. Then you just need to do `git pull` and it should be fine, I always build the UI before commit anyway so you wont need to do that.

I think the composer way because of `composer project create` does not include the `.git` so you cant just do a git pull.

**Comment by lcherone** [comment]
So for a script which is setup already:

- Move the `./plinker/database.db` out of the project.
  - `mv ./plinker/database.db /var/www/database.db`

If you want you could also move the `./config.ini` file if you want to keep the password etc.

Then remove everything..
 - `rm -Rf /var/www/html && mkdir /var/www/html`

Then pull down the git version (add the SSH key to your github account first), then:

 - `git clone git@github.com:lcherone/Conext.git /var/www/html/.`

Then from the /var/www/html folder run `composer setup`

Then move the database back:
 - `mv /var/www/database.db  /var/www/.plinker/database.db`

From then on, your be able to just do `git pull` and get the latest changes.

**Comment by Meywether** [comment]
Nice thx! Safe it and wanna try it!

**Comment by lcherone** [comment]
np, only thing which might change is the `./config.ini` as it has the `System Modules (effects UI menu)` items in, which is where im adding features.
So soon logs, files and metadata might need adding to the end of:
```
lxd="containers","images","operations","profiles","networks","devices","certificates","storage","ssh-keys"`
```

**Comment by Meywether** [comment]
@ the database file i do not have to edit anything?

**Comment by lcherone** [comment]
na its an sqlite file, it holds, the ssh keys, device entries, tasks, email setup, api etc but will "mutate" as needed if I change anything, keep it though if you have linked keys or devices, otherwise you dont need to back it up.. LXD holds everything it needs.
