### ISSUE TITLE
<UI> Enhancement container description

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#82]
Hi lcherone,
Within container settings page a field with description would be really nice!!!
best regards
Meywether

**Comment by lcherone** [comment]
So a description for the container?

I could add another tab/section which you could put multiple key/values, which would then go in the `user.*` properties?

What you think, or you just want description on the config tab?

**Comment by Meywether** [comment]
Mmh I didnt thought about it. Would be also nice but a small field with description as in the device section e.g. at the disc tab would be enough for me at first. So within the description i can also use whitespaces which i can not use in the containername.

**Comment by lcherone** [comment]
Just added..

Cant be added upon creation, there is no option for it.
