### ISSUE TITLE
BUG <UI> List Error 

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#84]
Hi lcherone, 

found a bug within the UI inside the Container -> ID Tab.

After toggling some of them on I saw that I toggled one false, the first one. After clicking on it, the last one was toggled.

![2018-06-11 18-46-14](https://user-images.githubusercontent.com/39849054/41245392-31bb7eb2-6da8-11e8-9288-c05d26658063.gif)

Sorry for creatins such a small video. But it was visible!

Best regards!
Meywether

**Comment by lcherone** [comment]
Thanks for reporting..

But that's an older version not sure which but you need to update, that bugs been fixed, also the attributes aligning up horizontally :/ in this commit: https://github.com/lcherone/Conext/commit/1cf77b23bbfcced56841fbf7fa0c9220bbd6ad54#diff-e3aaa3eb7494ac3493a885c0e1444086R138

You're also missing out on the awesome SSH Keys feature ;p

p.s.. whats going on with the UI? its not fitting in :/

![screencast-10 158 250 203-3000-2018 06 11-19-34-14](https://user-images.githubusercontent.com/3892806/41250439-df2effa0-6dae-11e8-80c1-9f7afb17d77a.gif)

**Comment by Meywether** [comment]
I just do a clean update installation and I will test this bug again!

**Comment by lcherone** [comment]
Are you using a VM?.. you're breaking my heart ;p

The project will install fine in a 18.04 container (w privileged & nesting)..

**Comment by Meywether** [comment]
> Are you using a VM?.. you're breaking my heart ;p

The project will install fine in a 18.04 container (w privileged & nesting).. also if you use git you wont need to keep doing fresh installs.

You are totally right, just want to get all of that nasty bugs :) starting from zero makes it easier.

Hey, I do not install Linux from zero again. Savepoints in HyperV are very helpfull XD ^^

**Comment by lcherone** [comment]
Your windows too, so Windows -> VM -> Container -> Container might be tricky sorting the network out.

Yeah, there will be many bugs until 1.0.0, I need to look into if you can force `.git` for `composer project create`, then it will be easy to update.

**Comment by Meywether** [comment]
Networking is indeed not a problem,
But for now I have to stop because I ran several times into the same issue I never got before:
![image](https://user-images.githubusercontent.com/39849054/41251642-cff9eb9c-6dba-11e8-97b9-a97c3fe91581.png)
And my internet connection works fine.
Mhh I have to test it tomorrow in more detail.
My opinion is Manus manum lavat. One hand washes the other. Or: You help me a lot with conext, and the minimum I could do is, helping you as much as I can !
👍

**Comment by lcherone** [comment]
No, I appreciate your feedback.

I can't seem to get that error hopefully it was just a one off, and that 300 secs is not the limit, else ill need to see about doing more in the `install.sh` script first, 

 - I have added `--keep-vcs` to the composer project create part and tested it and it maintains the `.git` woop.. so once installed you only need to go to `/var/www/html` now and do a `git pull` to get any updates, which is cool.

**Comment by Meywether** [comment]
> I have added --keep-vcs to the composer project create part and tested it and it maintains the .git woop.. so once installed you only need to go to /var/www/html now and do a git pull to get any updates, which is cool.

Indeed very cool! I gonna test it tomorrow! Thanks !!!

**Comment by Meywether** [comment]
Hiho good morning,
git pull seems to work -> already up to date
installation on clean ubuntu -> works
ui map bug -> yeah gone!
Best regards
Meywether

**Comment by lcherone** [comment]
Noice, ill close this issue
