### ISSUE TITLE
Enhancement install sh

### ISSUE THREAD

**Issue by Meywether** [lcherone/Conext#85]
Hi lcherone,
I just run into an issue while installing conext on a clean ubuntu 1804 desktop with minimal installlations.

>  curl not found error

I suggest to add # apt install curl to install.sh

Best regards
Meywether

**Comment by Meywether** [comment]
Hi,
same error on 1804 Desktop Minimal Installation with git!

> git not found

Suggest to add `apt install git` to install.sh`

Best regards
Meywether

**Comment by lcherone** [comment]
Thanks, yeah ive added it now, so should be all good. tbh I thought it was already in there.
